language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
before_script:
  - cp test/config/test_credentials.example.yml test/config/test_credentials.yml
script: rake test
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "BujeXOGqK0vfgLzQop2G/IpRnUwCoz5RTuhbms6GMEQDeZGps7f+pbvdpq5/\ntdrWhjZkTs/YZi2ww4HkDV6Wer4+FKf59yleBfkMyluKM93/xst8xBkSLMtv\nYNg7uDvD07XwKuoQYjifv+pwXoNO1mQjwLKLtozJw4cpdm0syDE="
